# /home/daniohlala/Desktop python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

__author__ = "Daniela Valdez"
__email__ = "dani.ohlala@gmail.com"

#-------------------------------------------------------------------------------------------------#

def fib(n):		# Función que calcula el n-esimo elemento de la sucesión de Fibonacci
	if n < 2:
		return n
	else:
		return fib(n-1) + fib(n-2)

i = 2 
elem = 0
sum = 0

while elem <= 4000000:
	elem = fib(i)
	if elem % 2 == 0:
		sum = sum + elem
	i = i + 1

print(sum)
